coverage:
  precision: 2
  round: down
  range: '75...100'
  status:
    patch:
      default:
        # basic
        target: 75%
        threshold: 10%
        if_ci_failed: error #success, failure, error, ignore
    project:
      default:
        target: 75%
        threshold: 10%
        flags:
          - Apex
      Apex:
        flags:
          - Apex
ignore:
  - 'sfdx-source/CustomMetadataLoader/main/default/staticresources/**'
