# Unique name for this workflow
name: On Push

# Definition when the workflow should run
on:
  workflow_dispatch:
  push:
    #paths-ignore:
    #- 'sfdx-project.json'
    #- 'README.md'
    #- 'docs/**'
    #- 'doc-assets/**'
    #- '.github/**'
    paths:
      - 'sfdx-source/**'
      - 'pmd/**'
      - 'config/**'
      - '.vscode/**'
      - '.prettier*'

# Jobs to be executed
jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      # Checkout the source code
      - name: 'Checkout source code'
        uses: actions/checkout@v4

      - name: 'Setup node'
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: 'Install NPM'
        run: npm ci

      # Prettier formatting
      - name: 'Code formatting verification with Prettier'
        run: npm run prettier:verify:apex

  pmd-analysis-download:
    runs-on: ubuntu-latest
    needs: format-check
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      # Checkout the source code
      - name: 'Checkout source code'
        uses: actions/checkout@v4

      # Install PMD
      - name: 'Install PMD'
        run: |
          PMD_VERSION=$(curl -s https://api.github.com/repos/pmd/pmd/releases/latest | grep '.tag_name' | sed 's:.*/::' | sed 's:",::')
          wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F$PMD_VERSION/pmd-dist-$PMD_VERSION-bin.zip
          unzip pmd-dist-$PMD_VERSION-bin.zip -d ~
          mv ~/pmd-bin-$PMD_VERSION ~/pmd
          ~/pmd/bin/pmd --version

      # Run PMD scan
      - name: 'Run PMD scan'
        run: ~/pmd/bin/pmd check --dir sfdx-source/CustomMetadataLoader --rulesets pmd/deployRules.xml --format text --cache .pmdCache --no-progress --minimum-priority "Medium Low"

  pmd-analysis-action:
    runs-on: ubuntu-latest
    needs: pmd-analysis-download
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      # Checkout the source code
      - name: 'Checkout source code'
        uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: pmd/pmd-github-action@v1
        id: pmd
        with:
          rulesets: 'pmd/deployRules.xml'
          analyzeModifiedFilesOnly: false
          version: 'latest'
          createGitHubAnnotations: true
          sourcePath: 'sfdx-source/CustomMetadataLoader'
          uploadSarifReport: false

      # Check for PMD violations
      - name: 'Check for PMD violations'
        if: steps.pmd.outputs.violations != 0
        run: exit 1
